### ISSUE TITLE
flutter 构建 ld: library not found for -lfake_wechat

### ISSUE THREAD

**Issue by ZetaChow** [v7lin/fake_wechat#11]
xcode 真机调试没问题，但是打包上传的时候，提示 ld: library not found for -lfake_wechat错误，请问如果解决。谢谢！！

**Comment by v7lin** [comment]
打包命令呢？flutter build ios --no-codesign？

**Comment by ZetaChow** [comment]
应该不是您的包的问题，我估计是xcode10的打包问题，没有把Pods引入
我看到了别人的解决办法 ，晚些时候我试试看是不是这个原因造成的https://github.com/flutter/flutter/issues/18305

**Comment by ZetaChow** [comment]
问题在于 flutter打包上传到App Store时，没有将Pods的关联文件正确的关联到工程中
