### ISSUE TITLE
微信分享带有url的封面图

### ISSUE THREAD

**Issue by deepsadness** [v7lin/fake_wechat#14]
博主的库写的很好。不过微信分享只能分享Uint8List的data,可以添加一下分享url形式的封面图吗？

**Comment by v7lin** [comment]
使用图片缓存库或者自己写个http请求吧

**Comment by deepsadness** [comment]
> 使用图片缓存库或者自己写个http请求吧

Flutter有什么推荐的图片缓存库吗？现在用原生的Image。加载完了图片。。也不知道怎么取出来😢

**Comment by v7lin** [comment]
保留意见不作推荐，可以到 pub.dev 上找

**Comment by deepsadness** [comment]
> 保留意见不作推荐，可以到 pub.dev 上找

好的。感谢🙏
