### ISSUE TITLE
请问，微信登录授权成功和失败的方法回调是什么?

### ISSUE THREAD

**Issue by itMrc** [v7lin/fake_wechat#15]
_auth = _wechat.authResp().listen(_listenAuth)；弹起授权页后点击同意/拒绝，回调_listenAuth都没有执行，可能是什么原因呢？

**Comment by v7lin** [comment]
调用注册方法了吗？

**Comment by CodeGather** [comment]
> 调用注册方法了吗？

我调用了注册，但是登录的时候返回0和null
但是我把scope改成WechatScope.SNSAPI_BASE
报错说是此公众号并没有这些scope的权限10005
用户信息可以获取到，二维码也没有问题，其他都没有问题
开放平台的账号是认证过的

**Comment by v7lin** [comment]
1. 监听要在授权前注册
2. 有可能是因为账号刚认证的原因，等会儿，或者杀死并重启微信APP

**Comment by CodeGather** [comment]
@v7lin 我是和你的demo写的一样

**Comment by CodeGather** [comment]
@v7lin 问题已解决，你的demo代码建议修改下，其实是已经成功了，只是拿错了数据成功后当然没有errorMsg
```
String content = 'auth: ${resp.errorCode} ${resp.errorMsg}';
//我添加的代码
print("--${resp.country}--${resp.lang}--${resp.state}---${resp.code}");
    _showTips('登录', content);

**Comment by v7lin** [comment]
@CodeGather 😀提个pr吧？
