### ISSUE TITLE
ios 无法使用

### ISSUE THREAD

**Issue by jlcool** [v7lin/fake_wechat#22]
提示：
-canOpenURL: failed for URL: "weixinULAPI://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
已经配置了 URL Types和LSApplicationQueriesSchemes

**Comment by v7lin** [comment]
^_^!!! 哈 ... 我要回归 Android 了，Flutter太让我失望了 ... 除了日常工作开发需要之外，我基本不会在为 Flutter 贡献代码了 ...

**Comment by v7lin** [comment]
一年了，整整一年了，WebView控件依然无法正常使用 ...

**Comment by jlcool** [comment]
😅

**Comment by v7lin** [comment]
applink没配置

**Comment by jlcool** [comment]
研究并配置universalLink后可以使用了
