### ISSUE TITLE
不支持WechatOpenSDK1.8.6，希望尽快能更新，谢谢🙏

### ISSUE THREAD

**Issue by kevin-lr** [v7lin/fake_wechat#23]
WechaSDK1.8.6.1

1.UIWebview切换成WKWebview
2.支持Universal Link拉起微信以及返回App
3.移除MTA库

UIWebview将要被水果淘汰，提交到appstore会警告。

**Comment by v7lin** [comment]
可以先用 git 方式引入仓库，master 分支上已支持 1.8.6 了，只是文档未补充完善

**Comment by kevin-lr** [comment]
好的，希望pub那边也能更新。谢谢
