### ISSUE TITLE
分享GIF 在微信端查看为静态的问题

### ISSUE THREAD

**Issue by jkyeo** [v7lin/fake_wechat#3]
嗯～ 又是我，分享了GIF 出去，但是在微信端查看是静态图片。

**Comment by v7lin** [comment]
😂 升级0.2.0+1，我这边看就是动图啊

**Comment by v7lin** [comment]
你跑一下example就知道结果了

**Comment by v7lin** [comment]
看错了-_-|| … 我等会儿看看微信 …

**Comment by v7lin** [comment]
iOS？Android？

**Comment by jkyeo** [comment]
对 是微信，iOS 有问题。Android 还没测试。

**Comment by v7lin** [comment]
似乎知道问题节点了 … 下午回去添加一下GIF分享功能 …

**Comment by jkyeo** [comment]
出现以下两种情况：
1.分享GIF的时候我没有填写thumbnail，而在iOS 微信客户端将“静态图”保存至相册。打开相册查看，又是动态图了。
2.macOS 微信客户端查看为动态图。

所以综上，是否是生成thumbnail 的时候出问题了呢？

**Comment by v7lin** [comment]
不是那个问题，分享GIF图片，应该用emoji方式去分享。原来我没写分享emoji方法，现在正在写，稍后更新上去，不急 。。。

**Comment by v7lin** [comment]
GIF功能已修正，因为其他事情，暂时没时间使用image库压缩GIF图片，并且补上example的thumbdata。急用的话，可先以git方式引入库。5.5号前不能保证发布个版本到pub上
