### ISSUE TITLE
网页分享-shareWebpage

### ISSUE THREAD

**Issue by gj452652749** [v7lin/fake_wechat#30]
网页分享，当scene设置文WechatScene.SESSION，点击微信群没反应，现在还不支持分享到会话吗？
代码如下：
_wechat.shareWebpage(
                scene: WechatScene.SESSION,
                webpageUrl: 'https://www.baidu.com',
              );

**Comment by q876625596** [comment]
请问，这个问题解决了吗，我这边也有同样的问题
