### ISSUE TITLE
微信登录苹果审核失败

### ISSUE THREAD

**Issue by hanabi1224** [v7lin/fake_wechat#33]
要求不安装微信也可以微信登录，请问这个怎么解决？
Guideline 4.2.3 - Design - Minimum Functionality

We were required to install the WeChat app before we could log in via WeChat. Users should be able to log in with WeChat and access their accounts without having to install any additional apps. If you would like to offer authentication through WeChat, please use a mechanism that allows users to log in with WeChat from within your app without first having to install an additional app.

**Comment by v7lin** [comment]
```dart
  wechat_kit:
    git:
      url: https://github.com/v7lin/fake_wechat.git
      ref: ios
```

**Comment by hanabi1224** [comment]
好的，我试下隐藏掉，多谢
