### ISSUE TITLE
sendReq failed for wechat app signature check failed

### ISSUE THREAD

**Issue by RowgerGo** [v7lin/fake_wechat#39]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.17.0-3.2.pre, on Microsoft Windows [Version 10.0.18363.778], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!

前面几分钟还能授权登录，后面就报错了
```
sendReq failed for wechat app signature check failed
```

**Comment by v7lin** [comment]
请检查签名
