### ISSUE TITLE
分享的图片要保存在微信可获取到的目录下？

### ISSUE THREAD

**Issue by jlcool** [v7lin/fake_wechat#8]
图片放temp和document都无法分享，保存到storage才可以分享，那demo里就有误了，还有ios没有storage吧，ios还没试，应该保存到哪呢？

**Comment by v7lin** [comment]
午休时间我再看看谁情况

**Comment by v7lin** [comment]
微信Android SDK确实是需要这样的，无法使用FileProvider解决这个问题，微信Android SDK自身问题，iOS就没这个限制了
如果不了解Android机制，请使用
````
dependencies:
  fake_path_provider: ^0.0.1+1
````

**Comment by v7lin** [comment]
如果你是分享小图，可以使用旧版非文件路径方式分享。换文件路径分享是分享大图用的

**Comment by jlcool** [comment]
非常感谢，已经改保存到storage
